### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by MateuszKaczmarczyk** [oskopek/javaanpr#28]
When I'm trying to recogonize car plates from jpg, I'm getting ArrayIndexOutOfBoundsException. Below is the code and error.

Code:

```
Intelligence intel = new Intelligence();
CarSnapshot carSnap = new CarSnapshot("D:/rejestracja.jpg");
String numberPlate = intel.recognize(carSnap, true);
System.out.println(numberPlate);
```

Error:

> java.lang.ArrayIndexOutOfBoundsException: 0 >= 0
>         at java.util.Vector.elementAt(Unknown Source)
>         at net.sf.javaanpr.intelligence.Intelligence.recognize(Intelligence.java:244)
>         at pl.anpr.test.MainClass.main(MainClass.java:49)

Error is in this line of Intelligence.java:
`similarityCost = ((RecognizedPattern)rc.getPatterns().elementAt(0)).getCost();`
So it's look like rc.getPatterns() returns empty collection. 

I tried with different images, and error is occuring every time. I'm using lastest version of JavaANPR and default settings.

**Comment by oskopek** [comment]
Hey, could you please upload your `config.xml` and possibly even the image you are testing against? Thanks for reporting the issue!

**Comment by MateuszKaczmarczyk** [comment]
config.xml and example photos I used are below.
The only thing I changed in config.xml is path to syntax file, it's because it couldn't find syntax file with default path, so I moved it and changed path.

config.xml:
> <?xml version="1.0" encoding="UTF-8"?>
> 
> 
> <!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
> <properties>
>     <comment>Global configuration file for the Automatic Number Plate
>         Recognition System
>     </comment>
> 
>     
> 
>     
>     <entry key="photo_adaptivethresholdingradius">7</entry>
>     
> 
>     
> 
>     
>     <entry key="intelligence_skewdetection">0</entry>
>     
> 
> 
>     
> 
>     <entry key="intelligence_numberOfBands">3</entry>
>     
>     <entry key="intelligence_numberOfPlates">3</entry>
>     
>     <entry key="intelligence_numberOfChars">20</entry>
>     
> 
>     
> 
>     <entry key="intelligence_minimumChars">5</entry>
>     
>     <entry key="intelligence_maximumChars">15</entry>
>     
>     <entry key="intelligence_maxCharWidthDispersion">0.5</entry>
>     
>     <entry key="intelligence_minPlateWidthHeightRatio">0.5</entry>
>     
>     <entry key="intelligence_maxPlateWidthHeightRatio">15.0</entry>
>     
> 
>     
> 
>     <entry key="intelligence_minCharWidthHeightRatio">0.1</entry>
>     
>     <entry key="intelligence_maxCharWidthHeightRatio">0.92</entry>
>     
>     <entry key="intelligence_maxBrightnessCostDispersion">0.161</entry>
>     
>     <entry key="intelligence_maxContrastCostDispersion">0.1</entry>
>     
>     <entry key="intelligence_maxHueCostDispersion">0.145</entry>
>     
>     <entry key="intelligence_maxSaturationCostDispersion">0.24</entry>
>     
>     <entry key="intelligence_maxHeightCostDispersion">0.2</entry>
>     
>     <entry key="intelligence_maxSimilarityCostDispersion">100.0</entry>
>     
> 
>     
> 
>     <entry key="char_normalizeddimensions_x">8</entry>
>     
>     <entry key="char_normalizeddimensions_y">13</entry>
>     
> 
>     
>     <entry key="char_learnAlphabetPath">/alphabets/alphabet_8x13</entry>
> 
>     
>     <entry key="char_resizeMethod">1</entry>
>     
> 
>     
>     <entry key="char_featuresExtractionMethod">0</entry>
>     
> 
>     
>     <entry key="intelligence_classification_method">0</entry>
>     
> 
>     
> 
>     <entry key="char_neuralNetworkPath">neuralnetworks/network_avgres_813_map.xml</entry>
>     
>     <entry key="neural_maxk">8000</entry>
>     
>     <entry key="neural_eps">0.07</entry>
>     
>     <entry key="neural_lambda">0.05</entry>
>     
>     <entry key="neural_micro">0.5</entry>
>     
>     <entry key="neural_topology">20</entry>
>     
> 
>     
> 
>     
>     <entry key="intelligence_syntaxanalysis">2</entry>
>     
>     <entry key="intelligence_syntaxDescriptionFile">syntax.xml</entry>
> 
>     
> 
>     <entry key="carsnapshot_graphrankfilter">9</entry>
>     <entry key="carsnapshot_distributormargins">25</entry>
>     <entry key="carsnapshotgraph_peakDiffMultiplicationConstant">0.1</entry>
>     <entry key="carsnapshotgraph_peakfootconstant">0.55</entry>
> 
>     <entry key="bandgraph_peakDiffMultiplicationConstant">0.2</entry>
>     <entry key="bandgraph_peakfootconstant">0.55</entry>
> 
>     <entry key="platehorizontalgraph_detectionType">1</entry>
>     
>     <entry key="platehorizontalgraph_peakfootconstant">0.05</entry>
>     <entry key="plateverticalgraph_peakfootconstant">0.42</entry>
>     <entry key="plategraph_rel_minpeaksize">0.86</entry>
>     <entry key="plategraph_peakfootconstant">0.7</entry>
> 
> </properties>

Photos:
![rejestracja-po](https://cloud.githubusercontent.com/assets/16896670/17462833/406b9b60-5cb9-11e6-8fc3-3d01249eb609.jpg)
![rejestracja](https://cloud.githubusercontent.com/assets/16896670/17462839/5d9fbfae-5cb9-11e6-8b6d-c7301759b39d.jpg)

**Comment by MateuszKaczmarczyk** [comment]
Now I tried with another photo, and there is no exception, but result is: null. Photo that return null below: 
![rejestracja-astra-ok](https://cloud.githubusercontent.com/assets/16896670/17462845/8fa7a58e-5cb9-11e6-81cd-c11e4a67ca3e.jpg)

**Comment by oskopek** [comment]
Thanks for the bug report, I'll get to it as soon as possible.

**Comment by oskopek** [comment]
1. It's weird that the syntax file wasn't found.. how are you running your code? When I run the latest `master` version of JavaANPR with the default configuration, the syntax file is found just fine.

2. I just tested with your images:
* with the default syntax file, the last image wasn't recognized (hence the null), the others were, I think correctly, but still, I couldn't reproduce the exception.

3. When I used this syntax.xml:
```xml
<!DOCTYPE structure SYSTEM "src/main/resources/dtd/syntax.dtd">

<structure>
    <type name="poland">
        <char content="abcdefghijklmnopqrstuvwxyz"/>
        <char content="abcdefghijklmnopqrstuvwxyz"/>
        <char content="abcdefghijklmnopqrstuvwxyz"/>
        <char content="0123456789"/>
        <char content="0123456789"/>
        <char content="0123456789"/>
        <char content="0123456789"/>
        <char content="0123456789"/>
    </type>
    <type name="poland2">
        <char content="abcdefghijklmnopqrstuvwxyz"/>
        <char content="abcdefghijklmnopqrstuvwxyz"/>
        <char content="0123456789"/>
        <char content="0123456789"/>
        <char content="0123456789"/>
        <char content="abcdefghijklmnopqrstuvwxyz"/>
        <char content="abcdefghijklmnopqrstuvwxyz"/>
    </type>
</structure>
```
Almost all of them were mostly correct. Still no exceptions.

I pushed 2 new commits into master, try to rebuild with the newest version and see if the error still appears.

**Comment by MateuszKaczmarczyk** [comment]
Still the same error on first two photos, and third return null.
I think some problems may be caused by wrong project import. I created new project with only one class, and added jar (after running mvn clean install) of javaanpr, so i can use net.sf.javaanpr.* packages. First problem i've faced was:

> ERROR net.sf.javaanpr.intelligence.Parser - Failed to load from parser syntax description file
> java.io.FileNotFoundException: C:\prj\\anprtest\src\main\resources\dtd\syntax.dtd

And then, after fixing above error:

> java.lang.ArrayIndexOutOfBoundsException: 0 >= 00 >= 0
> 	at java.util.Vector.elementAt(Unknown Source)
> 	at net.sf.javaanpr.intelligence.Intelligence.recognize(Intelligence.java:244)
> 	at main.java.pl.anpr.MainClass.main(MainClass.java:12)
>

**Comment by oskopek** [comment]
I fixed the dtd loading issue.

I could not reproduce you're other error. It worked for me doing the following steps:

* Created a new project, with this in the Main.java file:
```java
package cz.matfyz.oskopek;

import net.sf.javaanpr.configurator.Configurator;
import net.sf.javaanpr.imageanalysis.CarSnapshot;
import net.sf.javaanpr.intelligence.Intelligence;

public class Main {

    public static void main(String[] args) throws Exception {
        Configurator.getConfigurator().loadConfiguration("cz/matfyz/oskopek/config.xml");
        Intelligence intel = new Intelligence();

        String[] imgs = {"img1.jpg", "img2.jpg", "img3.jpg"};
        for (String img : imgs) {
            CarSnapshot carSnap = new CarSnapshot("/home/oskopek/tmp/" + img);
            String numberPlate = intel.recognize(carSnap, true);
            System.out.println(img + ":\t" + numberPlate);
        }

    }
}
```

* The `src/cz/matfyz/oskopek/config.xml` file:
  * Copied over from the config file in `src/main/resources` (of JavaANPR). The only change is the syntax.xml file:
```xml
<entry key="intelligence_syntaxDescriptionFile">cz/matfyz/oskopek/syntax.xml</entry>
```

* The `src/cz/matfyz/oskopek/syntax.xml` file:
```xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE structure SYSTEM "https://raw.githubusercontent.com/oskopek/javaanpr/master/src/main/resources/dtd/syntax.dtd">

<structure>
    <type name="poland">
        <char content="abcdefghijklmnopqrstuvwxyz"/>
        <char content="abcdefghijklmnopqrstuvwxyz"/>
        <char content="abcdefghijklmnopqrstuvwxyz"/>
        <char content="0123456789"/>
        <char content="0123456789"/>
        <char content="0123456789"/>
        <char content="0123456789"/>
        <char content="0123456789"/>
    </type>
    <type name="poland2">
        <char content="abcdefghijklmnopqrstuvwxyz"/>
        <char content="abcdefghijklmnopqrstuvwxyz"/>
        <char content="0123456789"/>
        <char content="0123456789"/>
        <char content="0123456789"/>
        <char content="abcdefghijklmnopqrstuvwxyz"/>
        <char content="abcdefghijklmnopqrstuvwxyz"/>
    </type>
</structure>
```

**Resulting output**:
```
img1.jpg:	null
img2.jpg:	PO082CC
img3.jpg:	NNI12742
```

**Comment by MateuszKaczmarczyk** [comment]
I tried to run this project on Linux OS (Ubuntu) and everything seems to be ok, there is no exception. Output is the same:

```
img1.jpg:   null
img2.jpg:   PO082CC
img3.jpg:   NNI12742
```

However on Windows 10 still "java.lang.ArrayIndexOutOfBoundsException: 0 >= 0". Maybe it's OS fault, or maybe - different version of Java or Maven?

I'm going to run JavaANPR on Raspberry Pi (Linux, Raspbian), so i think it will be working there. For now, I will work on Linux.
Thank you for help, now there are no configuration problems (like missing syntax file), and I can develop my application.

**Comment by oskopek** [comment]
Couldn't reproduce issue on Windows 7, JDK8. Closing as "wontfix".
